<?php
/**
 * @var \Tada\Shopback\Block\ShopbackTracking $block
 */
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Tada_Shopback/global-tracking":
            {
                "cookieTTL" : <?= $block->escapeJs($block->getCookieTTL()); ?>,
                "shopbackUrl": "<?= $block->escapeJs($block->getShopbackUrl()); ?>",
                "shopbackTransactionParameter": "<?= $block->escapeJs($block->getTransactionParameter()); ?>"
            }
        }
    }
</script>
